name: Chatops
on:
  issue_comment:
    types: [created]

jobs:
  command-dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/lint') || startsWith(github.event.comment.body, '/stage')
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1.1.3
        with:
          commands: lint, stage
          permission: admin
          issue-type: pull-request
          named-args: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ github.GITHUB_TOKEN }}
